name: setup nodeJs and python 
description: this action can be used to setup nodeJs and python
inputs:
  python-version:
     description: to provide the python version
     required: true
     default: '3.x'
  node-version:
    description: to provide the node version
    required: true
    default: '18.x'
runs:
  using: 'composite'
  steps:
   - name: setup node
     uses: actions/setup-node@v4
     with:
       node-version: 18.x
   - name: setup python
     uses: actions/setup-python@v4
     with:
       python-version: 3.x