name: setup nodeJs and python 
description: this action can be used to setup nodeJs and python
runs:
  using: 'composite'
  steps:
   - name: setup node
     uses: actions/setup-node@v4
     with:
       node-version: 18.x
   - name: setup python
     uses: actions/setup-python@v4
     with:
       python-version: 3.x